### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by ThanhByKyTa** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#11]
L 04/04/2018 - 09:45:11: [SM] Blaming: zombiereloaded.smx
L 04/04/2018 - 09:45:11: [SM] Call stack trace:
L 04/04/2018 - 09:45:11: [SM]   [0] ThrowNativeError
L 04/04/2018 - 09:45:11: [SM]   [1] Line 91, zr/api/api.inc::APIValidateClientIndex
L 04/04/2018 - 09:45:11: [SM]   [2] Line 84, zr/api/infect.api.inc::APIIsClientHuman
L 04/04/2018 - 09:45:11: [SM]   [4] ZR_IsClientHuman
L 04/04/2018 - 09:45:11: [SM]   [5] Line 94, zr_customclaws.sp::Arms
L 04/04/2018 - 09:45:11: [SM]   [6] Line 79, zr_customclaws.sp::pasado
L 04/04/2018 - 09:45:12: [SM] Exception reported: Client 3 must be alive.
L 04/04/2018 - 09:45:12: [SM] Blaming: zombiereloaded.smx
L 04/04/2018 - 09:45:12: [SM] Call stack trace:
L 04/04/2018 - 09:45:12: [SM]   [0] ThrowNativeError
L 04/04/2018 - 09:45:12: [SM]   [1] Line 91, zr/api/api.inc::APIValidateClientIndex
L 04/04/2018 - 09:45:12: [SM]   [2] Line 84, zr/api/infect.api.inc::APIIsClientHuman
L 04/04/2018 - 09:45:12: [SM]   [4] ZR_IsClientHuman
L 04/04/2018 - 09:45:12: [SM]   [5] Line 94, zr_customclaws.sp::Arms
L 04/04/2018 - 09:45:12: [SM]   [6] Line 79, zr_customclaws.sp::pasado
L 04/04/2018 - 12:15:00: Error log file session closed.

**Comment by ThanhByKyTa** [comment]
last update ...
L 04/15/2018 - 21:14:19: [SM] Blaming: zombiereloaded.smx
L 04/15/2018 - 21:14:19: [SM] Call stack trace:
L 04/15/2018 - 21:14:19: [SM]   [0] ThrowNativeError
L 04/15/2018 - 21:14:19: [SM]   [1] Line 91, zr/api/api.inc::APIValidateClientIndex
L 04/15/2018 - 21:14:19: [SM]   [2] Line 84, zr/api/infect.api.inc::APIIsClientHuman
L 04/15/2018 - 21:14:19: [SM]   [4] ZR_IsClientHuman
L 04/15/2018 - 21:14:19: [SM]   [5] Line 94, zr_customclaws.sp::Arms
L 04/15/2018 - 21:14:19: [SM]   [6] Line 79, zr_customclaws.sp::pasado

**Comment by Franc1sco** [comment]
That is about zr_customclaws plugin and not zombiereloaded plugin.
