### ISSUE TITLE
Scrip Error

### ISSUE THREAD

**Issue by ThanhByKyTa** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#17]
//// zombiereloaded.sp
//
// zr/volfeatures/voltools.inc(116) : warning 219: local variable "volumeIndex" shadows a variable at a preceding level
// zr/volfeatures/voltools.inc(221) : warning 219: local variable "volumeIndex" shadows a variable at a preceding level
// zr/volfeatures/volanticamp.inc(80) : warning 219: local variable "timer" shadows a variable at a preceding level
// zr/volfeatures/volfeatures.inc(378) : warning 219: local variable "volumeIndex" shadows a variable at a preceding level
// zr/volfeatures/volfeatures.inc(388) : warning 219: local variable "volumeIndex" shadows a variable at a preceding level
// zr/volfeatures/volfeatures.inc(462) : warning 219: local variable "volumeIndex" shadows a variable at a preceding level
// zr/volfeatures/volfeatures.inc(551) : warning 219: local variable "volumeIndex" shadows a variable at a preceding level
// Code size:           361504 bytes
// Data size:          1022200 bytes
// Stack/heap size:      16384 bytes
// Total requirements: 1400088 bytes
//
// 7 Warnings.
//
// Compilation Time: 2.36 sec
// ----------------------------------------

Press enter to exit ...

**Comment by RAYs3T** [comment]
Those are just warnings. You can ignore it.

"shadows a variable" means a global variable with the same name as a local one exist. So the local one shadows the global one.
