### ISSUE TITLE
Help me Compiler 1.10

### ISSUE THREAD

**Issue by ByKyTa** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#20]
//// zombiereloaded.sp
//
// C:\Users\ByKyTa\Desktop\1\include\sdktools_sound.inc(570) : warning 219: local variable "sample" shadows a variable at a preceding level
// zr/paramparser.inc(438) : error 163: indeterminate array size in "sizeof" expression (symbol "paramString")
// zr/paramparser.inc(471) : error 163: indeterminate array size in "sizeof" expression (symbol "paramString")
// zr/paramparser.inc(527) : error 163: indeterminate array size in "sizeof" expression (symbol "str")
// zr/weapons/weapons.inc(764) : error 017: undefined symbol "offsActiveWeapon"
//
// 4 Errors.
//
// Compilation Time: 0.75 sec
// ----------------------------------------

**Comment by oylsister** [comment]
Tell us more about your sourcemod version, it has 4 numbers after 1.10 (for example sm 1.10 6459)
