### ISSUE TITLE
New round market opened problem

### ISSUE THREAD

**Issue by MissXecutioner** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#25]
L 11/08/2020 - 01:03:47: [SM] Exception reported: Array index out-of-bounds (index 6, limit 6)
L 11/08/2020 - 01:03:47: [SM] Blaming: ohp_zombiereloaded.smx
L 11/08/2020 - 01:03:47: [SM] Call stack trace:
L 11/08/2020 - 01:03:47: [SM] [1] Line 1092, zr/weapons/zmarket.inc::ZMarketCookiesToArray
L 11/08/2020 - 01:03:47: [SM] [2] Line 1152, zr/weapons/zmarket.inc::ZMarketRebuy
L 11/08/2020 - 01:03:47: [SM] [3] Line 209, zr/weapons/zmarket.inc::ZMarketCheckRebuy
L 11/08/2020 - 01:03:47: [SM] [4] Line 177, zr/weapons/zmarket.inc::ZMarketOnClientSpawnPost
L 11/08/2020 - 01:03:47: [SM] [5] Line 373, zr/weapons/weapons.inc::WeaponsOnClientSpawnPost
L 11/08/2020 - 01:03:47: [SM] [6] Line 218, zr/event.inc::EventPlayerSpawnPost

How fix this ?

**Comment by Franc1sco** [comment]
I found the issue, I will upload the fix asap.

**Comment by Franc1sco** [comment]
It should be fixed with the latest commit https://github.com/Franc1sco/sm-zombiereloaded-3-Franug-Edition
