### ISSUE TITLE
Invalid client index. (0)

### ISSUE THREAD

**Issue by Septembers** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#27]
22 "ZR Class Fix" (3.1) by Franc1sco franug
23 "Zombie:Reloaded" (3.5.1 Franug edition) by Greyscale | Richard Helgeby and Franc1sco franug

L 01/18/2021 - 14:15:39: [SM] Exception reported: Invalid client index. (0)
L 01/18/2021 - 14:15:39: [SM] Blaming: zombiereloaded.smx
L 01/18/2021 - 14:15:39: [SM] Call stack trace:
L 01/18/2021 - 14:15:39: [SM]   [0] ThrowNativeError
L 01/18/2021 - 14:15:39: [SM]   [1] Line 74, zr/api/api.inc::APIValidateClientIndex
L 01/18/2021 - 14:15:39: [SM]   [2] Line 83, zr/api/class.api.inc::APISelectClientClass
L 01/18/2021 - 14:15:39: [SM]   [4] ZR_SelectClientClass
L 01/18/2021 - 14:15:39: [SM]   [5] Line 135, E:\Github\sm-zombiereloaded-3-Franug-Edition\optional plugins\zr_classfix.sp::SetDefaultClass
L 01/18/2021 - 14:15:39: [SM]   [6] Line 126, E:\Github\sm-zombiereloaded-3-Franug-Edition\optional plugins\zr_classfix.sp::Timer_SetDefaultClass

**Comment by Franc1sco** [comment]
Plugin updated, try now.
