### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Truyn** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#40]
L 03/26/2022 - 13:24:46: [SM] Exception reported: Script execution timed out
L 03/26/2022 - 13:24:46: [SM] Blaming: zombiereloaded.smx
L 03/26/2022 - 13:24:46: [SM] Call stack trace:
L 03/26/2022 - 13:24:46: [SM]   [1] Line 858, zr/weapons/weapons.inc::WeaponsRemoveClientGrenades
L 03/26/2022 - 13:24:46: [SM]   [2] Line 933, zr/weapons/weapons.inc::WeaponsRemoveAllClientWeapons
L 03/26/2022 - 13:24:46: [SM]   [3] Line 777, zr/infect.inc::InfectHumanToZombie
L 03/26/2022 - 13:24:46: [SM]   [4] Line 351, zr/infect.inc::InfectOnClientHurt
L 03/26/2022 - 13:24:46: [SM]   [5] Line 246, zr/event.inc::EventPlayerHurt
L 03/26/2022 - 13:27:26: [SM] Exception reported: Script execution timed out
L 03/26/2022 - 13:27:26: [SM] Blaming: zombiereloaded.smx
L 03/26/2022 - 13:27:26: [SM] Call stack trace:
L 03/26/2022 - 13:27:26: [SM]   [1] Line 858, zr/weapons/weapons.inc::WeaponsRemoveClientGrenades
L 03/26/2022 - 13:27:26: [SM]   [2] Line 933, zr/weapons/weapons.inc::WeaponsRemoveAllClientWeapons
L 03/26/2022 - 13:27:26: [SM]   [3] Line 777, zr/infect.inc::InfectHumanToZombie
L 03/26/2022 - 13:27:26: [SM]   [4] Line 351, zr/infect.inc::InfectOnClientHurt
L 03/26/2022 - 13:27:26: [SM]   [5] Line 246, zr/event.inc::EventPlayerHurt
L 03/26/2022 - 13:33:16: Error log file session closed.

**Comment by Truyn** [comment]
// Force player to drop all weapons on infect, disabling this will strip weapons instead.
// Default: "1"
zr_infect_weapons_drop "0"

a value of 1 is often given to revs and dependent modes

**Comment by Truyn** [comment]
@Franc1sco 
Thanks for the replies and quick support, I think you should not mention at all that you are supporting a mod that in fact is not.

No useful updates or fixes.
hype for hype

**Comment by Truyn** [comment]
For several years, not fixing a mistake with classes, etc., this is fucked up

**Comment by Franc1sco** [comment]
I dont have the obligation of fix your issues for free and with the unrespectful that you have. This is a hobby, not a job. If you are in a hurry then pay for it or learn to fix it yourself.
