### ISSUE TITLE
SourceMod 1.11 compile

### ISSUE THREAD

**Issue by Ketz1337** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#45]
Are you going to update the compile of the plugin with SourceMod version 1.11 at sometime?

![csgo_zm_compile_11](https://user-images.githubusercontent.com/23225942/182040455-947ec97d-bfd8-4876-9029-9ff015ba618f.png)

**Comment by oqyh** [comment]
need to rewrite + new syntax 
i can do that but it take time im lazy xD

**Comment by vitacell** [comment]
Today we have ChatGPT and all AI stuff, we don't need lazy people anymore.
