### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Meowmurmur** [Franc1sco/sm-zombiereloaded-3-Franug-Edition#9]
L 02/05/2017 - 11:27:54: [SM] Exception reported: Invalid timer handle 14460113 (error 3)
L 02/05/2017 - 11:27:54: [SM] Blaming: zombiereloaded.smx
L 02/05/2017 - 11:27:54: [SM] Call stack trace:
L 02/05/2017 - 11:27:54: [SM]   [0] KillTimer
L 02/05/2017 - 11:27:54: [SM]   [1] Line 187, zr/soundeffects/ambientsounds.inc::AmbientSoundsRestart
L 02/05/2017 - 11:27:54: [SM]   [2] Line 131, zr/soundeffects/ambientsounds.inc::AmbientSoundsOnRoundStart
L 02/05/2017 - 11:27:54: [SM]   [3] Line 79, zr/soundeffects/soundeffects.inc::SEffectsOnRoundStart
L 02/05/2017 - 11:27:54: [SM]   [4] Line 89, zr/event.inc::EventRoundStart

**Comment by MindaugasR** [comment]
Have same issue.
